{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/leonardo99i/Inteligencia_Artificial/blob/main/busca_cega.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Busca em Profundidade-DFS\n",
        "\n",
        "class no:\n",
        "\n",
        "  def __init__(self, adjacentes: list):\n",
        "    self.cor = 'Branco'\n",
        "\n",
        "#variáveis custo final e inicial para o vetor de tempo\n",
        "\n",
        "    self.custo_inicial = 0\n",
        "    self.custo_final = 0\n",
        "    self.antecessor = None\n",
        "    self.adjacentes = adjacentes\n",
        "\n",
        "#criação de gets de custo inicial, final e cor\n",
        "\n",
        "  def get_cor(self):\n",
        "    return self.cor\n",
        "\n",
        "  def get_custo_inicial(self):\n",
        "    return self.custo_inicial\n",
        "\n",
        "  def get_custo_final(self):\n",
        "    return self.custo_final\n",
        "\n",
        "  def get_adjacentes(self):\n",
        "    return self.adjacentes\n",
        "\n",
        "#criação dos sets  custo inicial, final, antecessor e cor\n",
        "\n",
        "  def set_cor(self, cor : str):\n",
        "    self.cor = cor\n",
        "  \n",
        "  def set_custo_inicial(self, custo : float):\n",
        "    self.custo = custo_inicial\n",
        "\n",
        "  def set_custo_final(self, custo : float):\n",
        "    self.custo = custo_final\n",
        "\n",
        "  def set_antecessor(self, antecessor):\n",
        "    self.antecessor = antecessor\n",
        "\n",
        "#criação do método dfs que recebe o grafo e uma lista de nó\n",
        "\n",
        "def dfs(grafo: list):\n",
        "  for no_grafo in grafo:\n",
        "    if no_grafo.get_cor()== 'Branco':\n",
        "      visita_no(no_grafo)\n",
        "\n",
        "#deixar o nó atual com a cor azul, incrementar a variável de tempo  \n",
        "#e tb inserir no custo atual\n",
        "\n",
        "def visita_no(no_atual : no):\n",
        "\n",
        "#variável global\n",
        "\n",
        "  global tempo\n",
        "  no_atual.set_cor('Azul')\n",
        "  tempo  += 1\n",
        "  no_atual.set_custo_inicial(tempo)\n",
        "\n",
        "#criar um for para percorrer cada nó adjacente\n",
        "\n",
        "  for no_temp in no_atual.get_adjacente():\n",
        "\n",
        "#se a cor for Branco então faz-se a chamada recursiva para esse nó\n",
        "\n",
        "      if no_temp.get_cor() == 'Branco':\n",
        "        no_temp.set_antecessor(no_atual)\n",
        "\n",
        "#recursividade\n",
        "\n",
        "        visita_no(no_temp)\n",
        "\n",
        "#por ultimo fora do if e do for a cor atual recebe vermelho e incrementa\n",
        "#o tempo final\n",
        "\n",
        "  no_atual.set_cor('Vermelho')\n",
        "  tempo += 1\n",
        "  no_atual.set_custo_final(tempo)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        " \n",
        "\n",
        "\n",
        "\n",
        "  \n",
        " \n",
        "\n",
        "  \n",
        "\n"
      ],
      "metadata": {
        "id": "CShb_BxngX-b"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "7OXXrCa91b1H"
      },
      "outputs": [],
      "source": [
        "#Busca em Largura-BFS\n",
        "\n",
        "class no:\n",
        "\n",
        "  def __init__(self, adjacentes: list):\n",
        "    self.cor = 'Branco'\n",
        "    self.custo = 0\n",
        "    self.antecessor = None\n",
        "    self.adjacentes = adjacentes\n",
        "\n",
        "  def get_cor(self):\n",
        "    return self.cor\n",
        "\n",
        "  def get_custo(self):\n",
        "    return self.custo\n",
        "\n",
        "  def get_adjacentes(self):\n",
        "    return self.adjaentes\n",
        "\n",
        "  def set_cor(self, cor: str):\n",
        "    self.cor = cor\n",
        "\n",
        "  def set_custo(self, custo: float):\n",
        "    self.custo = custo\n",
        "\n",
        "  def set_antecessor(self, antecessor):\n",
        "     self.antecessor = antecessor\n",
        "\n",
        "# script da busca bfs\n",
        "\n",
        "def bfs(no_inicial:no):\n",
        "  no_inicial.set_cor('Azul')\n",
        "\n",
        "# criar um fila para inserir o nó nessa fila\n",
        "\n",
        "  fila = [no_inicial]\n",
        "\n",
        "# verificar se a fila não estava vazia, ('len' = tamanho dessa fila)\n",
        "\n",
        "  while (len(fila)>0):\n",
        "\n",
        "# remover o primeiro elemento da fila\n",
        "\n",
        "    no_atual: no = fila.pop(0)\n",
        "\n",
        "# para cada nó adjacente coloca-se o nó atual e inserir na nessa lista\n",
        "\n",
        "    for no_temp in no_atual.get_adjacentes():\n",
        "      if no_temp.get_cor() == 'Branco':\n",
        "        no_temp.set_cor('Azul')\n",
        "        no_temp.set_custo(no_temp.get_custo()+1)\n",
        "        no_temp.set_antecessor(no_atual)\n",
        "        fila.append(no_temp)\n",
        "\n",
        "  no_atual.set_cor('Vermelho')\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "  \n",
        "\n",
        "  \n",
        "  \n",
        "\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "q12GqzAp9sPs"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}